-- E · 会员入场后场馆当前人数 +1
CREATE OR REPLACE TRIGGER trg_checkin_update_venue
AFTER INSERT ON CHECKINOUT
FOR EACH ROW
WHEN (NEW.CHECK_OUT_TIME IS NULL)
BEGIN
    UPDATE VENUE
    SET CURRENT_CAPACITY = NVL(CURRENT_CAPACITY, 0) + 1
    WHERE VENUE_ID = :NEW.VENUE_ID;
END;
/
