-- E · 入场/退场时自动更新场馆当前人数
-- 入场 INSERT（CHECK_OUT_TIME IS NULL）→ CURRENT_CAPACITY +1
-- 退场 UPDATE（CHECK_OUT_TIME 从 NULL 变为非 NULL）→ CURRENT_CAPACITY -1
CREATE OR REPLACE TRIGGER trg_checkin_update_venue
AFTER INSERT OR UPDATE OF CHECK_OUT_TIME ON CHECKINOUT
FOR EACH ROW
BEGIN
    -- 入场：新增记录且未退场
    IF INSERTING AND :NEW.CHECK_OUT_TIME IS NULL THEN
        UPDATE VENUE
        SET CURRENT_CAPACITY = NVL(CURRENT_CAPACITY, 0) + 1
        WHERE VENUE_ID = :NEW.VENUE_ID;
    END IF;

    -- 退场：CHECK_OUT_TIME 从 NULL 更新为有值
    IF UPDATING('CHECK_OUT_TIME') AND :OLD.CHECK_OUT_TIME IS NULL AND :NEW.CHECK_OUT_TIME IS NOT NULL THEN
        UPDATE VENUE
        SET CURRENT_CAPACITY = GREATEST(NVL(CURRENT_CAPACITY, 0) - 1, 0)
        WHERE VENUE_ID = :NEW.VENUE_ID;
    END IF;
END;
/
