-- H · 为支付订单补充会员归属（便于无券下单与会员侧过滤）
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PAYMENT_ORDER ADD MEMBER_ID NUMBER(10)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    UPDATE PAYMENT_ORDER o
    SET MEMBER_ID = (
      SELECT v.MEMBER_ID FROM VOUCHER v WHERE v.VOUCHER_ID = o.VOUCHER_ID
    )
    WHERE o.MEMBER_ID IS NULL AND o.VOUCHER_ID IS NOT NULL';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

COMMIT;
