-- H · 为支付订单补充会员归属（无券订单也能显示会员ID）
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PAYMENT_ORDER ADD MEMBER_ID NUMBER(10)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN
      RAISE;
    END IF;
END;
/

-- 有券：从优惠券回填
UPDATE PAYMENT_ORDER o
SET MEMBER_ID = (
  SELECT v.MEMBER_ID FROM VOUCHER v WHERE v.VOUCHER_ID = o.VOUCHER_ID
)
WHERE o.MEMBER_ID IS NULL AND o.VOUCHER_ID IS NOT NULL;

-- 无券：本系统下单时 BUSINESS_ORDER_ID = 会员ID，可作兜底回填
UPDATE PAYMENT_ORDER
SET MEMBER_ID = BUSINESS_ORDER_ID
WHERE MEMBER_ID IS NULL
  AND BUSINESS_ORDER_ID IS NOT NULL
  AND BUSINESS_ORDER_ID > 0;

COMMIT;
