-- SEED_USER_DEMO.sql
-- 演示账号种子（课设联调）。密码明文仅写在注释中，库内为 BCrypt 哈希。
-- 演示密码：Demo@123456
-- 在 SQL Developer / DBeaver 中用 F5 执行整份脚本。
-- 主键策略：云库无序列时使用 MAX+1（与后端样板一致）。
-- MEMBER.USER_ID 有唯一约束 UK_MEMBER_USER_ID：一个账号只能绑一名会员。

-- 1) 演示会员账号 demo_member
INSERT INTO USERS (
  USER_ID, LOGIN_NAME, PASSWORD_HASH, DISPLAY_NAME, STATUS, CREATED_AT, UPDATED_AT
)
SELECT
  NVL((SELECT MAX(USER_ID) FROM USERS), 0) + 1,
  'demo_member',
  '$2b$10$Tcc8wGAAKY.tiAUwrdBBqet5fz3eIWIwmFs54GT50TgZ7f3L6pl6a',
  '演示会员',
  '1',
  SYSDATE,
  SYSDATE
FROM dual
WHERE NOT EXISTS (
  SELECT 1 FROM USERS WHERE LOGIN_NAME = 'demo_member'
);

-- 优先：把尚未绑定账号的会员绑到 demo_member（仅当该账号尚未绑定任何人）
UPDATE MEMBER
SET USER_ID = (SELECT USER_ID FROM USERS WHERE LOGIN_NAME = 'demo_member')
WHERE MEMBER_ID = (
  SELECT MIN(m.MEMBER_ID) FROM MEMBER m WHERE m.USER_ID IS NULL
)
AND EXISTS (SELECT 1 FROM USERS WHERE LOGIN_NAME = 'demo_member')
AND NOT EXISTS (
  SELECT 1 FROM MEMBER WHERE USER_ID = (SELECT USER_ID FROM USERS WHERE LOGIN_NAME = 'demo_member')
);

-- 若仍无人绑定，则新建演示会员
INSERT INTO MEMBER (
  MEMBER_ID, NAME, PHONE_NUMBER, MEMBER_LEVEL, GENDER, REGISTER_DATE, STATUS, USER_ID
)
SELECT
  NVL((SELECT MAX(MEMBER_ID) FROM MEMBER), 0) + 1,
  '演示会员',
  '13800000001',
  '普通',
  'M',
  SYSDATE,
  '1',
  (SELECT USER_ID FROM USERS WHERE LOGIN_NAME = 'demo_member')
FROM dual
WHERE EXISTS (SELECT 1 FROM USERS WHERE LOGIN_NAME = 'demo_member')
AND NOT EXISTS (
  SELECT 1 FROM MEMBER WHERE USER_ID = (SELECT USER_ID FROM USERS WHERE LOGIN_NAME = 'demo_member')
);

-- 2) 演示教练账号 demo_coach
INSERT INTO USERS (
  USER_ID, LOGIN_NAME, PASSWORD_HASH, DISPLAY_NAME, STATUS, CREATED_AT, UPDATED_AT
)
SELECT
  NVL((SELECT MAX(USER_ID) FROM USERS), 0) + 1,
  'demo_coach',
  '$2b$10$Tcc8wGAAKY.tiAUwrdBBqet5fz3eIWIwmFs54GT50TgZ7f3L6pl6a',
  '演示教练',
  '1',
  SYSDATE,
  SYSDATE
FROM dual
WHERE NOT EXISTS (
  SELECT 1 FROM USERS WHERE LOGIN_NAME = 'demo_coach'
);

UPDATE COACH
SET USER_ID = (SELECT USER_ID FROM USERS WHERE LOGIN_NAME = 'demo_coach')
WHERE COACH_ID = (
  SELECT MIN(c.COACH_ID) FROM COACH c WHERE c.USER_ID IS NULL
)
AND EXISTS (SELECT 1 FROM USERS WHERE LOGIN_NAME = 'demo_coach')
AND NOT EXISTS (
  SELECT 1 FROM COACH WHERE USER_ID = (SELECT USER_ID FROM USERS WHERE LOGIN_NAME = 'demo_coach')
);

COMMIT;

-- 验证：
-- SELECT u.LOGIN_NAME, m.MEMBER_ID, m.NAME FROM USERS u
-- LEFT JOIN MEMBER m ON m.USER_ID = u.USER_ID
-- WHERE u.LOGIN_NAME IN ('demo_member', 'demo_coach');
