-- H · 演示数据（可选，本地库订单/优惠券为空时可执行）
-- 连接：使用本地/组内 Oracle（账号密码见本地 appsettings.Local.json，勿提交）
-- 注意：PAYMENT_STATUS 只能是：待支付 / 已支付 / 已取消

INSERT INTO VOUCHER (VOUCHER_ID, MEMBER_ID, VOUCHER_TYPE, DISCOUNT_VALUE, VALID_UNTIL, STATUS)
SELECT NVL((SELECT MAX(VOUCHER_ID) FROM VOUCHER), 0) + 1,
       (SELECT MIN(MEMBER_ID) FROM MEMBER),
       '生日福利券',
       50,
       ADD_MONTHS(SYSDATE, 1),
       '0'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM VOUCHER);

INSERT INTO VOUCHER (VOUCHER_ID, MEMBER_ID, VOUCHER_TYPE, DISCOUNT_VALUE, VALID_UNTIL, STATUS)
SELECT NVL((SELECT MAX(VOUCHER_ID) FROM VOUCHER), 0) + 1,
       (SELECT MIN(MEMBER_ID) FROM MEMBER),
       '续费折扣券',
       30,
       ADD_MONTHS(SYSDATE, 2),
       '0'
FROM DUAL
WHERE (SELECT COUNT(*) FROM VOUCHER) < 2;

INSERT INTO PRICE_LIST (PRICE_ID, PRODUCT_TYPE, STANDARD_PRICE, PRICE_UPDATE_TIME)
SELECT NVL((SELECT MAX(PRICE_ID) FROM PRICE_LIST), 0) + 1,
       'MEMBER_CARD_RENEW',
       299,
       SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PRICE_LIST);

INSERT INTO PAYMENT_ORDER (ORDER_ID, BUSINESS_ORDER_ID, TOTAL_AMOUNT, PAYMENT_STATUS, CREATE_TIME, PAYMENT_FINISH_TIME, VOUCHER_ID)
SELECT NVL((SELECT MAX(ORDER_ID) FROM PAYMENT_ORDER), 0) + 1,
       90001,
       299,
       '已支付',
       SYSDATE,
       SYSDATE,
       (SELECT MIN(VOUCHER_ID) FROM VOUCHER)
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PAYMENT_ORDER);

INSERT INTO PAYMENT_DETAIL (DETAIL_ID, ORDER_ID, PRICE_ID, TRANSACTION_PRICE, QUANTITY, SUBTOTAL_AMOUNT)
SELECT NVL((SELECT MAX(DETAIL_ID) FROM PAYMENT_DETAIL), 0) + 1,
       (SELECT MIN(ORDER_ID) FROM PAYMENT_ORDER),
       (SELECT MIN(PRICE_ID) FROM PRICE_LIST),
       299,
       1,
       299
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PAYMENT_DETAIL);

COMMIT;

SELECT fn_calc_order_payable((SELECT MIN(ORDER_ID) FROM PAYMENT_ORDER)) AS payable FROM DUAL;
