-- J · 日程管理模块演示数据
-- 会员日程：member_id 使用已存在的 1/2/3；SCHEDULE_TYPE 'G' 团操 / 'P' 私教；STATUS '0' 待上 / '1' 已上 / '2' 已取消
-- 教练日程：coach_id 使用已存在的 101/3001；STATUS 中文 '正常' / '已完成'
-- 可重复执行（先按 SCHEDULE_ID 范围清理再插入）

-- ===== 会员日程 =====
DELETE FROM MEMBER_SCHEDULE WHERE SCHEDULE_ID BETWEEN 6001 AND 6004;

INSERT INTO MEMBER_SCHEDULE (SCHEDULE_ID, MEMBER_ID, SCHEDULE_DATE, SCHEDULE_START, SCHEDULE_END, SCHEDULE_TYPE, SOURCE_RECORD_ID, STATUS)
VALUES (6001, 1, TRUNC(SYSDATE + 1), TRUNC(SYSDATE + 1) + INTERVAL '8' HOUR,  TRUNC(SYSDATE + 1) + INTERVAL '9' HOUR,  'G', NULL, '0');

INSERT INTO MEMBER_SCHEDULE (SCHEDULE_ID, MEMBER_ID, SCHEDULE_DATE, SCHEDULE_START, SCHEDULE_END, SCHEDULE_TYPE, SOURCE_RECORD_ID, STATUS)
VALUES (6002, 1, TRUNC(SYSDATE + 2), TRUNC(SYSDATE + 2) + INTERVAL '10' HOUR, TRUNC(SYSDATE + 2) + INTERVAL '11' HOUR, 'P', NULL, '0');

INSERT INTO MEMBER_SCHEDULE (SCHEDULE_ID, MEMBER_ID, SCHEDULE_DATE, SCHEDULE_START, SCHEDULE_END, SCHEDULE_TYPE, SOURCE_RECORD_ID, STATUS)
VALUES (6003, 2, TRUNC(SYSDATE + 1), TRUNC(SYSDATE + 1) + INTERVAL '14' HOUR, TRUNC(SYSDATE + 1) + INTERVAL '15' HOUR, 'G', NULL, '1');

INSERT INTO MEMBER_SCHEDULE (SCHEDULE_ID, MEMBER_ID, SCHEDULE_DATE, SCHEDULE_START, SCHEDULE_END, SCHEDULE_TYPE, SOURCE_RECORD_ID, STATUS)
VALUES (6004, 3, TRUNC(SYSDATE + 1), TRUNC(SYSDATE + 1) + INTERVAL '9' HOUR,  TRUNC(SYSDATE + 1) + INTERVAL '10' HOUR, 'P', NULL, '2');

-- ===== 教练日程 =====
DELETE FROM COACH_SCHEDULE WHERE SCHEDULE_ID BETWEEN 7001 AND 7004;

INSERT INTO COACH_SCHEDULE (SCHEDULE_ID, COACH_ID, SCHEDULE_DATE, SCHEDULE_START, SCHEDULE_END, SCHEDULE_TYPE, SOURCE_RECORD_ID, STATUS)
VALUES (7001, 101,  TRUNC(SYSDATE + 1), TRUNC(SYSDATE + 1) + INTERVAL '8' HOUR,  TRUNC(SYSDATE + 1) + INTERVAL '9' HOUR,  'G', NULL, '正常');

INSERT INTO COACH_SCHEDULE (SCHEDULE_ID, COACH_ID, SCHEDULE_DATE, SCHEDULE_START, SCHEDULE_END, SCHEDULE_TYPE, SOURCE_RECORD_ID, STATUS)
VALUES (7002, 101,  TRUNC(SYSDATE + 1), TRUNC(SYSDATE + 1) + INTERVAL '10' HOUR, TRUNC(SYSDATE + 1) + INTERVAL '11' HOUR, 'P', NULL, '正常');

INSERT INTO COACH_SCHEDULE (SCHEDULE_ID, COACH_ID, SCHEDULE_DATE, SCHEDULE_START, SCHEDULE_END, SCHEDULE_TYPE, SOURCE_RECORD_ID, STATUS)
VALUES (7003, 3001, TRUNC(SYSDATE + 2), TRUNC(SYSDATE + 2) + INTERVAL '14' HOUR, TRUNC(SYSDATE + 2) + INTERVAL '15' HOUR, 'P', NULL, '已完成');

INSERT INTO COACH_SCHEDULE (SCHEDULE_ID, COACH_ID, SCHEDULE_DATE, SCHEDULE_START, SCHEDULE_END, SCHEDULE_TYPE, SOURCE_RECORD_ID, STATUS)
VALUES (7004, 101,  TRUNC(SYSDATE + 1), TRUNC(SYSDATE + 1) + INTERVAL '16' HOUR, TRUNC(SYSDATE + 1) + INTERVAL '17' HOUR, 'G', NULL, '正常');

COMMIT;
