// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901081901_BaselineCurrentSchema")]
    partial class BaselineCurrentSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("USING_NLS_COMP")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ID");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("AVATAR_URL");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("DISPLAY_NAME");

                    b.Property<string>("LoginName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("LOGIN_NAME");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("STATUS")
                        .IsFixedLength();

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("UserId");

                    b.HasIndex("LoginName")
                        .IsUnique()
                        .HasFilter("\"LOGIN_NAME\" IS NOT NULL");

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Capacitylog", b =>
                {
                    b.Property<int>("CapacityLogId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CAPACITY_LOG_ID");

                    b.Property<DateTime?>("LogTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("LOG_TIMESTAMP")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<decimal?>("OccupancyRate")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("OCCUPANCY_RATE");

                    b.Property<int?>("RecordedCapacity")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RECORDED_CAPACITY");

                    b.Property<int>("RecordedCount")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RECORDED_COUNT");

                    b.Property<int>("VenueId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VENUE_ID");

                    b.HasKey("CapacityLogId")
                        .HasName("SYS_C008523");

                    b.HasIndex("VenueId");

                    b.ToTable("CAPACITYLOG", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Cardproduct", b =>
                {
                    b.Property<int>("ProductId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("CARD_TYPE")
                        .IsFixedLength();

                    b.HasKey("ProductId")
                        .HasName("SYS_C008606");

                    b.ToTable("CARDPRODUCT", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Checkinout", b =>
                {
                    b.Property<int>("CheckInOutId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CHECK_IN_OUT_ID");

                    b.Property<int?>("CardId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CARD_ID");

                    b.Property<DateTime>("CheckInTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("CHECK_IN_TIME")
                        .HasDefaultValueSql("SYSDATE ");

                    b.Property<string>("CheckOutMode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("CHECK_OUT_MODE")
                        .HasDefaultValueSql("'0' ")
                        .IsFixedLength();

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("DATE")
                        .HasColumnName("CHECK_OUT_TIME");

                    b.Property<int>("VenueId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VENUE_ID");

                    b.HasKey("CheckInOutId")
                        .HasName("SYS_C008516");

                    b.HasIndex("CardId");

                    b.HasIndex("VenueId");

                    b.ToTable("CHECKINOUT", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Coach", b =>
                {
                    b.Property<int>("CoachId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("COACH_ID");

                    b.Property<string>("CoachName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("COACH_NAME");

                    b.Property<string>("CoachSummary")
                        .HasColumnType("CLOB")
                        .HasColumnName("COACH_SUMMARY");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("DATE")
                        .HasColumnName("HIRE_DATE");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<string>("Sex")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("SEX");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("SPECIALTY");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'在职' ");

                    b.Property<int?>("UserId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ID");

                    b.HasKey("CoachId")
                        .HasName("SYS_C008343");

                    b.HasIndex(new[] { "UserId" }, "UK_COACH_USER_ID")
                        .IsUnique()
                        .HasFilter("\"USER_ID\" IS NOT NULL");

                    b.ToTable("COACH", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CoachSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SCHEDULE_ID");

                    b.Property<int>("CoachId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("COACH_ID");

                    b.Property<DateTime>("ScheduleDate")
                        .HasColumnType("DATE")
                        .HasColumnName("SCHEDULE_DATE");

                    b.Property<DateTime>("ScheduleEnd")
                        .HasColumnType("DATE")
                        .HasColumnName("SCHEDULE_END");

                    b.Property<DateTime>("ScheduleStart")
                        .HasColumnType("DATE")
                        .HasColumnName("SCHEDULE_START");

                    b.Property<string>("ScheduleType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("SCHEDULE_TYPE");

                    b.Property<int?>("SourceRecordId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SOURCE_RECORD_ID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'正常'\r\n                       ");

                    b.HasKey("ScheduleId")
                        .HasName("SYS_C008640");

                    b.HasIndex("CoachId");

                    b.ToTable("COACH_SCHEDULE", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CountCardExtension", b =>
                {
                    b.Property<int>("CardId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CARD_ID");

                    b.Property<int>("RemainingCount")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("REMAINING_COUNT");

                    b.Property<int>("TotalCounts")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("TOTAL_COUNTS");

                    b.HasKey("CardId")
                        .HasName("SYS_C008616");

                    b.ToTable("COUNT_CARD_EXTENSION", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CourseType", b =>
                {
                    b.Property<int>("TypeId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TYPE_ID");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TYPE_NAME");

                    b.HasKey("TypeId")
                        .HasName("SYS_C008339");

                    b.ToTable("COURSE_TYPE", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EMP_ID");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("EMP_NAME");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("PHONE");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("ROLE");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'0'\r\n")
                        .IsFixedLength()
                        .HasComment("1-在职，0-离职");

                    b.Property<int?>("UserId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ID");

                    b.HasKey("EmpId")
                        .HasName("SYS_C008425");

                    b.HasIndex(new[] { "UserId" }, "UK_EMPLOYEE_USER_ID")
                        .IsUnique()
                        .HasFilter("\"USER_ID\" IS NOT NULL");

                    b.ToTable("EMPLOYEE", null, t =>
                        {
                            t.HasComment("员工信息");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Equipment", b =>
                {
                    b.Property<int>("EquipId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EQUIP_ID");

                    b.Property<string>("EquipName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("EQUIP_NAME");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("DATE")
                        .HasColumnName("PURCHASE_DATE");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'正常'");

                    b.Property<string>("VenueId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("VENUE_ID");

                    b.HasKey("EquipId")
                        .HasName("SYS_C008427");

                    b.ToTable("EQUIPMENT", null, t =>
                        {
                            t.HasComment("健身器材");
                        });
                });

            modelBuilder.Entity("Domain.Entities.GroupCourseBooking", b =>
                {
                    b.Property<int>("BookingId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BOOKING_ID");

                    b.Property<string>("BookingStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("BOOKING_STATUS")
                        .HasDefaultValueSql("'0' ")
                        .IsFixedLength();

                    b.Property<DateTime?>("BookingTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("BOOKING_TIME")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<int>("CourseId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("COURSE_ID");

                    b.Property<int>("MemberId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MEMBER_ID");

                    b.HasKey("BookingId")
                        .HasName("SYS_C008630");

                    b.HasIndex("CourseId");

                    b.HasIndex(new[] { "MemberId", "CourseId" }, "UK_MEMBER_COURSE")
                        .IsUnique();

                    b.ToTable("GROUP_COURSE_BOOKING", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Groupcourse", b =>
                {
                    b.Property<int>("CourseId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("COURSE_ID");

                    b.Property<int>("CoachId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("COACH_ID");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("COURSE_NAME");

                    b.Property<string>("CourseSummary")
                        .HasColumnType("CLOB")
                        .HasColumnName("COURSE_SUMMARY");

                    b.Property<short?>("CurrentCapacity")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5)
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("CURRENT_CAPACITY")
                        .HasDefaultValueSql("0 ");

                    b.Property<short>("MaxCapacity")
                        .HasPrecision(5)
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("MAX_CAPACITY");

                    b.Property<string>("TimeSlotId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("TIME_SLOT_ID");

                    b.Property<int>("TypeId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TYPE_ID");

                    b.HasKey("CourseId")
                        .HasName("SYS_C008366");

                    b.HasIndex("CoachId");

                    b.HasIndex("TimeSlotId");

                    b.HasIndex("TypeId");

                    b.ToTable("GROUPCOURSE", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Inspectiontask", b =>
                {
                    b.Property<int>("TaskId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TASK_ID");

                    b.Property<int>("EmpId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EMP_ID");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("REMARK");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'待执行'");

                    b.Property<DateTime>("TaskTime")
                        .HasColumnType("DATE")
                        .HasColumnName("TASK_TIME");

                    b.Property<int>("VenueId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VENUE_ID");

                    b.HasKey("TaskId")
                        .HasName("SYS_C008435");

                    b.HasIndex("EmpId");

                    b.ToTable("INSPECTIONTASK", null, t =>
                        {
                            t.HasComment("卫生巡检任务");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MEMBER_ID");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("DATE")
                        .HasColumnName("BIRTHDAY");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("GENDER")
                        .IsFixedLength();

                    b.Property<string>("IdCard")
                        .HasMaxLength(18)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(18)")
                        .HasColumnName("ID_CARD");

                    b.Property<string>("MemberLevel")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("MEMBER_LEVEL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<DateTime?>("RegisterDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("REGISTER_DATE")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'1' ")
                        .IsFixedLength();

                    b.Property<int?>("UserId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ID");

                    b.HasKey("MemberId")
                        .HasName("SYS_C008487");

                    b.HasIndex(new[] { "PhoneNumber" }, "SYS_C008488")
                        .IsUnique()
                        .HasFilter("\"PHONE_NUMBER\" IS NOT NULL");

                    b.HasIndex(new[] { "IdCard" }, "SYS_C008489")
                        .IsUnique()
                        .HasFilter("\"ID_CARD\" IS NOT NULL");

                    b.HasIndex(new[] { "UserId" }, "UK_MEMBER_USER_ID")
                        .IsUnique()
                        .HasFilter("\"USER_ID\" IS NOT NULL");

                    b.ToTable("MEMBER", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MemberBenefitCard", b =>
                {
                    b.Property<int>("CardId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CARD_ID");

                    b.Property<string>("CardStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("CARD_STATUS")
                        .HasDefaultValueSql("'1' ")
                        .IsFixedLength();

                    b.Property<DateTime?>("IssueDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("ISSUE_DATE")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<int>("MemberId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MEMBER_ID");

                    b.Property<int?>("ProductId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRODUCT_ID");

                    b.HasKey("CardId")
                        .HasName("SYS_C008500");

                    b.HasIndex("MemberId");

                    b.HasIndex("ProductId");

                    b.ToTable("MEMBER_BENEFIT_CARD", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MemberSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SCHEDULE_ID");

                    b.Property<int>("MemberId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MEMBER_ID");

                    b.Property<DateTime>("ScheduleDate")
                        .HasColumnType("DATE")
                        .HasColumnName("SCHEDULE_DATE");

                    b.Property<DateTime>("ScheduleEnd")
                        .HasColumnType("DATE")
                        .HasColumnName("SCHEDULE_END");

                    b.Property<DateTime>("ScheduleStart")
                        .HasColumnType("DATE")
                        .HasColumnName("SCHEDULE_START");

                    b.Property<string>("ScheduleType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("SCHEDULE_TYPE")
                        .IsFixedLength();

                    b.Property<int?>("SourceRecordId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SOURCE_RECORD_ID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'1' ")
                        .IsFixedLength();

                    b.HasKey("ScheduleId")
                        .HasName("SYS_C008625");

                    b.HasIndex("MemberId");

                    b.ToTable("MEMBER_SCHEDULE", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PaymentDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DETAIL_ID");

                    b.Property<int>("OrderId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ORDER_ID");

                    b.Property<int>("PriceId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRICE_ID");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITY")
                        .HasDefaultValueSql("1 ");

                    b.Property<decimal>("SubtotalAmount")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("SUBTOTAL_AMOUNT");

                    b.Property<decimal>("TransactionPrice")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("TRANSACTION_PRICE");

                    b.HasKey("DetailId")
                        .HasName("SYS_C008660");

                    b.HasIndex("OrderId");

                    b.HasIndex("PriceId");

                    b.ToTable("PAYMENT_DETAIL", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PaymentOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ORDER_ID");

                    b.Property<int>("BusinessOrderId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BUSINESS_ORDER_ID");

                    b.Property<DateTime?>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("CREATE_TIME")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<DateTime?>("PaymentFinishTime")
                        .HasColumnType("DATE")
                        .HasColumnName("PAYMENT_FINISH_TIME");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("PAYMENT_STATUS");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("TOTAL_AMOUNT");

                    b.Property<int?>("VoucherId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VOUCHER_ID");

                    b.HasKey("OrderId")
                        .HasName("SYS_C008650");

                    b.HasIndex("VoucherId");

                    b.ToTable("PAYMENT_ORDER", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PersonalCourse", b =>
                {
                    b.Property<int>("PersonalCourseId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PERSONAL_COURSE_ID");

                    b.Property<int?>("CoachId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("COACH_ID");

                    b.Property<string>("CourseDescription")
                        .HasColumnType("CLOB")
                        .HasColumnName("COURSE_DESCRIPTION");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("COURSE_NAME");

                    b.HasKey("PersonalCourseId")
                        .HasName("SYS_C008643");

                    b.HasIndex("CoachId");

                    b.ToTable("PERSONAL_COURSE", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Personalpackage", b =>
                {
                    b.Property<int>("PackageId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PACKAGE_ID");

                    b.Property<int>("CoachId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("COACH_ID");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("DATE")
                        .HasColumnName("EXPIRE_DATE");

                    b.Property<int>("MemberId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MEMBER_ID");

                    b.Property<string>("PackageStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("PACKAGE_STATUS");

                    b.Property<int>("PersonalCourseId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PERSONAL_COURSE_ID");

                    b.Property<short>("RemainingSessions")
                        .HasPrecision(5)
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("REMAINING_SESSIONS");

                    b.Property<short>("TotalSessions")
                        .HasPrecision(5)
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("TOTAL_SESSIONS");

                    b.HasKey("PackageId");

                    b.HasIndex("CoachId");

                    b.HasIndex("PersonalCourseId");

                    b.ToTable("PERSONALPACKAGE", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PriceList", b =>
                {
                    b.Property<int>("PriceId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRICE_ID");

                    b.Property<DateTime?>("PriceUpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("PRICE_UPDATE_TIME")
                        .HasDefaultValueSql("SYSDATE\r\n");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("PRODUCT_TYPE");

                    b.Property<decimal>("StandardPrice")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("STANDARD_PRICE");

                    b.HasKey("PriceId")
                        .HasName("SYS_C008654");

                    b.ToTable("PRICE_LIST", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Ptbooking", b =>
                {
                    b.Property<int>("PtBookingId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PT_BOOKING_ID");

                    b.Property<DateTime>("BookingTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("BOOKING_TIME")
                        .HasDefaultValueSql("SYSDATE ");

                    b.Property<string>("CoachConfirmed")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("COACH_CONFIRMED")
                        .HasDefaultValueSql("'0' ")
                        .IsFixedLength();

                    b.Property<int>("CoachId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("COACH_ID");

                    b.Property<string>("MemberConfirmed")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("MEMBER_CONFIRMED")
                        .HasDefaultValueSql("'0' ")
                        .IsFixedLength();

                    b.Property<int>("MemberId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MEMBER_ID");

                    b.Property<int>("PackageId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PACKAGE_ID");

                    b.Property<DateTime>("SessionTime")
                        .HasColumnType("DATE")
                        .HasColumnName("SESSION_TIME");

                    b.HasKey("PtBookingId");

                    b.HasIndex("CoachId");

                    b.HasIndex("PackageId");

                    b.ToTable("PTBOOKING", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Repairrecord", b =>
                {
                    b.Property<int>("RecordId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RECORD_ID");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<int?>("EmpId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EMP_ID");

                    b.Property<int>("EquipId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EQUIP_ID");

                    b.Property<decimal?>("RepairCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(20,2)")
                        .HasColumnName("REPAIR_COST")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("ReportTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("REPORT_TIME")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'待处理'");

                    b.HasKey("RecordId")
                        .HasName("SYS_C008429");

                    b.HasIndex("EmpId");

                    b.HasIndex("EquipId");

                    b.ToTable("REPAIRRECORD", null, t =>
                        {
                            t.HasComment("器材维修记录");
                        });
                });

            modelBuilder.Entity("Domain.Entities.TimeCardExtension", b =>
                {
                    b.Property<int>("CardId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CARD_ID");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("DATE")
                        .HasColumnName("EXPIRE_DATE");

                    b.HasKey("CardId")
                        .HasName("SYS_C008609");

                    b.ToTable("TIME_CARD_EXTENSION", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TimeSlotInstance", b =>
                {
                    b.Property<string>("TimeSlotId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("TIME_SLOT_ID");

                    b.Property<DateTime>("StartTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("START_TIME");

                    b.Property<DateTime>("CourseDate")
                        .HasColumnType("DATE")
                        .HasColumnName("COURSE_DATE");

                    b.Property<DateTime>("EndTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("END_TIME");

                    b.HasKey("TimeSlotId", "StartTime", "CourseDate")
                        .HasName("SYS_C008356");

                    b.ToTable("TIME_SLOT_INSTANCE", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TimeSlotTemplate", b =>
                {
                    b.Property<string>("TimeSlotId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("TIME_SLOT_ID");

                    b.HasKey("TimeSlotId")
                        .HasName("SYS_C008350");

                    b.ToTable("TIME_SLOT_TEMPLATE", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VENUE_ID");

                    b.Property<short?>("CurrentCapacity")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5)
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("CURRENT_CAPACITY")
                        .HasDefaultValueSql("0 ");

                    b.Property<short>("MaxCapacity")
                        .HasPrecision(5)
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("MAX_CAPACITY");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("VENUE_NAME");

                    b.Property<string>("VenueStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("VENUE_STATUS")
                        .HasDefaultValueSql("'1' ")
                        .IsFixedLength();

                    b.HasKey("VenueId")
                        .HasName("SYS_C008495");

                    b.ToTable("VENUE", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Voucher", b =>
                {
                    b.Property<int>("VoucherId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VOUCHER_ID");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("DISCOUNT_VALUE");

                    b.Property<int>("MemberId")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MEMBER_ID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'0'\r\n")
                        .IsFixedLength()
                        .HasComment("0-未使用，1-已核销，2-已过期");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("DATE")
                        .HasColumnName("VALID_UNTIL");

                    b.Property<string>("VoucherType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("VOUCHER_TYPE");

                    b.HasKey("VoucherId")
                        .HasName("SYS_C008441");

                    b.ToTable("VOUCHER", null, t =>
                        {
                            t.HasComment("会员福利券记录表");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Capacitylog", b =>
                {
                    b.HasOne("Domain.Entities.Venue", "Venue")
                        .WithMany("Capacitylogs")
                        .HasForeignKey("VenueId")
                        .IsRequired()
                        .HasConstraintName("FK_CAPACITY_VENUE");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Domain.Entities.Checkinout", b =>
                {
                    b.HasOne("Domain.Entities.MemberBenefitCard", "Card")
                        .WithMany("Checkinouts")
                        .HasForeignKey("CardId")
                        .HasConstraintName("FK_CHECK_CARD");

                    b.HasOne("Domain.Entities.Venue", "Venue")
                        .WithMany("Checkinouts")
                        .HasForeignKey("VenueId")
                        .IsRequired()
                        .HasConstraintName("FK_CHECK_VENUE");

                    b.Navigation("Card");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Domain.Entities.Coach", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_COACH_USERS");
                });

            modelBuilder.Entity("Domain.Entities.CoachSchedule", b =>
                {
                    b.HasOne("Domain.Entities.Coach", "Coach")
                        .WithMany("CoachSchedules")
                        .HasForeignKey("CoachId")
                        .IsRequired()
                        .HasConstraintName("FK_SCHEDULE_COACH");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Domain.Entities.CountCardExtension", b =>
                {
                    b.HasOne("Domain.Entities.MemberBenefitCard", "Card")
                        .WithOne("CountCardExtension")
                        .HasForeignKey("Domain.Entities.CountCardExtension", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_COUNT_CARD");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_EMPLOYEE_USERS");
                });

            modelBuilder.Entity("Domain.Entities.GroupCourseBooking", b =>
                {
                    b.HasOne("Domain.Entities.Groupcourse", "Course")
                        .WithMany("GroupCourseBookings")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_BOOKING_COURSE");

                    b.HasOne("Domain.Entities.Member", "Member")
                        .WithMany("GroupCourseBookings")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_BOOKING_MEMBER");

                    b.Navigation("Course");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Domain.Entities.Groupcourse", b =>
                {
                    b.HasOne("Domain.Entities.Coach", "Coach")
                        .WithMany("Groupcourses")
                        .HasForeignKey("CoachId")
                        .IsRequired()
                        .HasConstraintName("FK_COURSE_COACH");

                    b.HasOne("Domain.Entities.TimeSlotTemplate", "TimeSlot")
                        .WithMany("Groupcourses")
                        .HasForeignKey("TimeSlotId")
                        .IsRequired()
                        .HasConstraintName("FK_COURSE_TIMESLOT");

                    b.HasOne("Domain.Entities.CourseType", "Type")
                        .WithMany("Groupcourses")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK_COURSE_TYPE");

                    b.Navigation("Coach");

                    b.Navigation("TimeSlot");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.Entities.Inspectiontask", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Emp")
                        .WithMany("Inspectiontasks")
                        .HasForeignKey("EmpId")
                        .IsRequired()
                        .HasConstraintName("FK_INSPECT_EMP");

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("Domain.Entities.Member", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_MEMBER_USERS");
                });

            modelBuilder.Entity("Domain.Entities.MemberBenefitCard", b =>
                {
                    b.HasOne("Domain.Entities.Member", "Member")
                        .WithMany("MemberBenefitCards")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_CARD_MEMBER");

                    b.HasOne("Domain.Entities.Cardproduct", "Product")
                        .WithMany("MemberBenefitCards")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_CARD_PRODUCT");

                    b.Navigation("Member");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.MemberSchedule", b =>
                {
                    b.HasOne("Domain.Entities.Member", "Member")
                        .WithMany("MemberSchedules")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_SCHEDULE_MEMBER");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Domain.Entities.PaymentDetail", b =>
                {
                    b.HasOne("Domain.Entities.PaymentOrder", "Order")
                        .WithMany("PaymentDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_DETAIL_ORDER");

                    b.HasOne("Domain.Entities.PriceList", "Price")
                        .WithMany("PaymentDetails")
                        .HasForeignKey("PriceId")
                        .IsRequired()
                        .HasConstraintName("FK_DETAIL_PRICE");

                    b.Navigation("Order");

                    b.Navigation("Price");
                });

            modelBuilder.Entity("Domain.Entities.PaymentOrder", b =>
                {
                    b.HasOne("Domain.Entities.Voucher", "Voucher")
                        .WithMany("PaymentOrders")
                        .HasForeignKey("VoucherId")
                        .HasConstraintName("FK_ORDER_VOUCHER");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Domain.Entities.PersonalCourse", b =>
                {
                    b.HasOne("Domain.Entities.Coach", "Coach")
                        .WithMany("PersonalCourses")
                        .HasForeignKey("CoachId")
                        .HasConstraintName("FK_PERSONAL_COURSE_COACH");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Domain.Entities.Personalpackage", b =>
                {
                    b.HasOne("Domain.Entities.Coach", "Coach")
                        .WithMany("Personalpackages")
                        .HasForeignKey("CoachId")
                        .IsRequired()
                        .HasConstraintName("FK_PP_COACH");

                    b.HasOne("Domain.Entities.PersonalCourse", "PersonalCourse")
                        .WithMany("Personalpackages")
                        .HasForeignKey("PersonalCourseId")
                        .IsRequired()
                        .HasConstraintName("FK_PACKAGE_PERSONAL_COURSE");

                    b.Navigation("Coach");

                    b.Navigation("PersonalCourse");
                });

            modelBuilder.Entity("Domain.Entities.Ptbooking", b =>
                {
                    b.HasOne("Domain.Entities.Coach", "Coach")
                        .WithMany("Ptbookings")
                        .HasForeignKey("CoachId")
                        .IsRequired()
                        .HasConstraintName("FK_PB_COACH");

                    b.HasOne("Domain.Entities.Personalpackage", "Package")
                        .WithMany("Ptbookings")
                        .HasForeignKey("PackageId")
                        .IsRequired()
                        .HasConstraintName("FK_PB_PACKAGE");

                    b.Navigation("Coach");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Domain.Entities.Repairrecord", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Emp")
                        .WithMany("Repairrecords")
                        .HasForeignKey("EmpId")
                        .HasConstraintName("FK_REPAIR_EMP");

                    b.HasOne("Domain.Entities.Equipment", "Equip")
                        .WithMany("Repairrecords")
                        .HasForeignKey("EquipId")
                        .IsRequired()
                        .HasConstraintName("FK_REPAIR_EQUIP");

                    b.Navigation("Emp");

                    b.Navigation("Equip");
                });

            modelBuilder.Entity("Domain.Entities.TimeCardExtension", b =>
                {
                    b.HasOne("Domain.Entities.MemberBenefitCard", "Card")
                        .WithOne("TimeCardExtension")
                        .HasForeignKey("Domain.Entities.TimeCardExtension", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TIME_CARD");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Domain.Entities.TimeSlotInstance", b =>
                {
                    b.HasOne("Domain.Entities.TimeSlotTemplate", "TimeSlot")
                        .WithMany("TimeSlotInstances")
                        .HasForeignKey("TimeSlotId")
                        .IsRequired()
                        .HasConstraintName("FK_TIMESLOT_TEMPLATE");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("Domain.Entities.Cardproduct", b =>
                {
                    b.Navigation("MemberBenefitCards");
                });

            modelBuilder.Entity("Domain.Entities.Coach", b =>
                {
                    b.Navigation("CoachSchedules");

                    b.Navigation("Groupcourses");

                    b.Navigation("PersonalCourses");

                    b.Navigation("Personalpackages");

                    b.Navigation("Ptbookings");
                });

            modelBuilder.Entity("Domain.Entities.CourseType", b =>
                {
                    b.Navigation("Groupcourses");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Navigation("Inspectiontasks");

                    b.Navigation("Repairrecords");
                });

            modelBuilder.Entity("Domain.Entities.Equipment", b =>
                {
                    b.Navigation("Repairrecords");
                });

            modelBuilder.Entity("Domain.Entities.Groupcourse", b =>
                {
                    b.Navigation("GroupCourseBookings");
                });

            modelBuilder.Entity("Domain.Entities.Member", b =>
                {
                    b.Navigation("GroupCourseBookings");

                    b.Navigation("MemberBenefitCards");

                    b.Navigation("MemberSchedules");
                });

            modelBuilder.Entity("Domain.Entities.MemberBenefitCard", b =>
                {
                    b.Navigation("Checkinouts");

                    b.Navigation("CountCardExtension");

                    b.Navigation("TimeCardExtension");
                });

            modelBuilder.Entity("Domain.Entities.PaymentOrder", b =>
                {
                    b.Navigation("PaymentDetails");
                });

            modelBuilder.Entity("Domain.Entities.PersonalCourse", b =>
                {
                    b.Navigation("Personalpackages");
                });

            modelBuilder.Entity("Domain.Entities.Personalpackage", b =>
                {
                    b.Navigation("Ptbookings");
                });

            modelBuilder.Entity("Domain.Entities.PriceList", b =>
                {
                    b.Navigation("PaymentDetails");
                });

            modelBuilder.Entity("Domain.Entities.TimeSlotTemplate", b =>
                {
                    b.Navigation("Groupcourses");

                    b.Navigation("TimeSlotInstances");
                });

            modelBuilder.Entity("Domain.Entities.Venue", b =>
                {
                    b.Navigation("Capacitylogs");

                    b.Navigation("Checkinouts");
                });

            modelBuilder.Entity("Domain.Entities.Voucher", b =>
                {
                    b.Navigation("PaymentOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
