-- 签到/签退进出场流水（容量日志页记录条）
-- 应用启动时也会自动尝试创建；若已存在可忽略。
CREATE TABLE CAPACITYMOVEMENT (
  MOVEMENT_ID NUMBER(10) PRIMARY KEY,
  VENUE_ID NUMBER(10) NOT NULL,
  MEMBER_ID NUMBER(10) NOT NULL,
  EVENT_TIME DATE NOT NULL,
  EVENT_TYPE VARCHAR2(1) NOT NULL,
  RECORDED_COUNT NUMBER(10) NOT NULL,
  OCCUPANCY_RATE NUMBER(5,2),
  CHECK_IN_OUT_ID NUMBER(10)
);
/
