-- D · 会员卡测试数据（仅本地空库备用，共享库请勿执行）
-- 组内共享 Oracle 已由 E 模块插入 1001/1002/1003 测试卡，D 模块直接查库自测即可。
-- 仅当本地库没有任何会员卡、且 MEMBER_ID=1 存在时，才执行本脚本。

-- 时效卡示例：CARD_ID=101，90 天内有效
INSERT INTO MEMBER_BENEFIT_CARD (CARD_ID, MEMBER_ID, ISSUE_DATE, CARD_STATUS, CARD_TYPE)
VALUES (101, 1, SYSDATE, '1', '1');

INSERT INTO TIME_CARD_EXTENSION (CARD_ID, EXPIRE_DATE)
VALUES (101, SYSDATE + 90);

-- 次卡示例：CARD_ID=102，共 20 次剩 15 次
INSERT INTO MEMBER_BENEFIT_CARD (CARD_ID, MEMBER_ID, ISSUE_DATE, CARD_STATUS, CARD_TYPE)
VALUES (102, 1, SYSDATE, '1', '0');

INSERT INTO COUNT_CARD_EXTENSION (CARD_ID, TOTAL_COUNTS, REMAINING_COUNT)
VALUES (102, 20, 15);

-- 验证
-- SELECT * FROM MEMBER_BENEFIT_CARD WHERE MEMBER_ID = 1;
-- SELECT fn_is_card_valid(101) FROM dual;
