-- J · 会员团课预约汇总视图
-- 注意：GROUP_COURSE_BOOKING 已重构，不再有 COURSE_ID 列，
--       改为 PACKAGE_ID 关联 GROUPPACKAGE（表名无下划线），再由 GROUPPACKAGE.COURSE_ID 关联 GROUPCOURSE。
CREATE OR REPLACE VIEW v_member_booking_summary AS
SELECT
    m.MEMBER_ID,
    m.NAME AS MEMBER_NAME,
    g.COURSE_NAME,
    b.BOOKING_TIME,
    b.BOOKING_STATUS
FROM MEMBER m
JOIN GROUP_COURSE_BOOKING b ON m.MEMBER_ID = b.MEMBER_ID
JOIN GROUPPACKAGE p ON b.PACKAGE_ID = p.PACKAGE_ID
JOIN GROUPCOURSE g ON p.COURSE_ID = g.COURSE_ID;
