-- J · 会员团课预约汇总视图
CREATE OR REPLACE VIEW v_member_booking_summary AS
SELECT
    m.MEMBER_ID,
    m.NAME AS MEMBER_NAME,
    g.COURSE_NAME,
    b.BOOKING_TIME,
    b.BOOKING_STATUS
FROM MEMBER m
JOIN GROUP_COURSE_BOOKING b ON m.MEMBER_ID = b.MEMBER_ID
JOIN GROUPCOURSE g ON b.COURSE_ID = g.COURSE_ID;
