-- D · 会员卡 CARD_ID 序列（办卡 INSERT 前取 NEXTVAL）
-- 验证：SELECT GYM_ADMIN.SEQ_MEMBER_BENEFIT_CARD.NEXTVAL FROM dual;

CREATE SEQUENCE GYM_ADMIN.SEQ_MEMBER_BENEFIT_CARD
  START WITH 160100
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
